spring.application.name=apiGateway

server.port=8098

# Configuracion de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# JWT Secret (misma que usarios en todos los servicios)
jwt.secret=SK_443ff638f8a74ba659cdb8336bfb5f91

# Gateway Discovery (para encontrar servicios automaticamente)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.instance.prefer-ip-address=true